package Constants;

public class Settings {
	//public static String BASE_PDF_URL = "https://test.wms2-pdf.descartes-finance.com/api/v1/";
	//public static String BASE_WMS_URL = "https://test.wms2-app.descartes-finance.com/api/v1/";
	//public static String GUEST_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJwcmltYXJ5Z3JvdXBzaWQiOiJERVNDQVJURVMiLCJuYW1laWQiOiIxMTU3IiwidW5pcXVlX25hbWUiOiIxMTU3IiwiZ2l2ZW5fbmFtZSI6Ikd1ZXN0IiwiZmFtaWx5X25hbWUiOiJVc2VyIiwicm9sZSI6Ikd1ZXN0IiwibmJmIjoxNjc1MDcyNzc1LCJleHAiOjE5OTA2NDIyOTUsImlhdCI6MTY3NTA3Mjc3NX0.KaPRhES4tn-iHGoMID80RnxHoKtbpCi5rzxJ_2PJuxs";
	//public static String ADMIN_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmltYXJ5Z3JvdXBzaWQiOiJERVNDQVJURVMiLCJuYW1laWQiOiIzIiwidW5pcXVlX25hbWUiOiIzIiwiZ2l2ZW5fbmFtZSI6IiIsImZhbWlseV9uYW1lIjoiIiwicm9sZSI6IlN1cGVyQWRtaW4iLCJpZHR5cCI6IkFwcE9ubHkiLCJuYmYiOjE3NTAzMzc0OTUsImV4cCI6MTkzOTYzOTg5NCwiaWF0IjoxNzUwMzM3NDk1fQ.O4NQ1aQREzKoTDlkQCiABpJufkw3zovsNmXaCHhIeRU";
	
	public static String BASE_PDF_URL = "http://localhost:8095/api/v1/";
	public static String BASE_WMS_URL = "http://localhost:63736/api/v1/";
	public static String GUEST_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6IkpXVCJ9.eyJwcmltYXJ5Z3JvdXBzaWQiOiJERVNDQVJURVMiLCJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiIxIiwiZ2l2ZW5fbmFtZSI6Ikd1ZXN0IiwiZmFtaWx5X25hbWUiOiJVc2VyIiwicm9sZSI6Ikd1ZXN0IiwibmJmIjoxNjc1MDcyMjU0LCJleHAiOjE5OTA2NDE3NzQsImlhdCI6MTY3NTA3MjI1NH0.1QCb5j3XAQRBRulgUiYNy_xFsE68x3DZtKaIczcOwlc";
	public static String ADMIN_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcmltYXJ5Z3JvdXBzaWQiOiJERVNDQVJURVMiLCJuYW1laWQiOiIzIiwidW5pcXVlX25hbWUiOiIzIiwiZ2l2ZW5fbmFtZSI6IlN1cGVyIiwiZmFtaWx5X25hbWUiOiJBZG1pbiIsInJvbGUiOiJTdXBlckFkbWluIiwiaWR0eXAiOiJBcHBPbmx5IiwibmJmIjoxNzAyODk4NzA5LCJleHAiOjIxNDQ3NDgzMDksImlhdCI6MTcwMjg5ODcwOX0.qurNwnatNjH3f4lMk5GMQ7Oc0Fsfyd5zXv1cLmwZj2w";
}